export const MEMBER_LOGIN_REQUEST='MEMBER_LOGIN_REQUEST'
export const MEMBER_LOGIN_SUCESS='MEMBER_LOGIN_SUCESS'
export const MEMBER_LOGIN_FAIL='MEMBER_LOGIN_FAIL'

export const MEMBER_REGISTER_REQUEST='MEMBER_REGISTER_REQUEST'
export const MEMBER_REGISTER_SUCESS='MEMBER_REGISTER_SUCESS'
export const MEMBER_REGISTER_FAIL='MEMBER_REGISTER_FAIL'


export const MEMBER_LIST_REQUEST='MEMBER_LIST_REQUEST'
export const MEMBER_LIST_SUCESS='MEMBER_LIST_SUCESS'
export const MEMBER_LIST_FAIL='MEMBER_LIST_FAIL'

export const MEMBER_DETAILS_REQUEST='MEMBER_DETAILS_REQUEST'
export const MEMBER_DETAILS_SUCESS='MEMBER_DETAILS_SUCESS'
export const MEMBER_DETAILS_FAIL='MEMBER_DETAILS_FAIL'